#!/bin/sh

# Load the Husky pre-commit hook script (assuming husky.sh is located in a known path)
. "$(dirname "$0")/_/husky.sh"

# Change to the 'src/portal-ng' directory
cd src/portal-ng

# Build and run tests
npm run build:tst && npm run test:single