export const pioneer=[
    {
        "S.No.": 1,
        "Name": "ASHRU MOCHAN BARAL",
        "ID": "2117070130200112",
        "Year": "2021-22",
        "Class": "pioneer",
        "Section": "A",
        "Overall Marks Obtained": "198",
        "Total Marks": "250",
        "Percentage": "79.20%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "8",
        "Enroll Section": "A"
    },
    {
        "S.No.": 2,
        "Name": "DUSHMANTA MAHARANA",
        "ID": "2117070130200011",
        "Year": "2021-22",
        "Class": "pioneer",
        "Section": "A",
        "Overall Marks Obtained": "178",
        "Total Marks": "250",
        "Percentage": "71.20%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "8",
        "Enroll Section": "A"
    },
    {
        "S.No.": 3,
        "Name": "PRIYABRATA BARIK",
        "ID": "2117070130200043",
        "Year": "2021-22",
        "Class": "pioneer",
        "Section": "A",
        "Overall Marks Obtained": "185",
        "Total Marks": "250",
        "Percentage": "74.00%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "8",
        "Enroll Section": "A"
    },
    {
        "S.No.": 4,
        "Name": "SHEETAL PRADHAN",
        "ID": "2117070130200009",
        "Year": "2021-22",
        "Class": "pioneer",
        "Section": "A",
        "Overall Marks Obtained": "188",
        "Total Marks": "250",
        "Percentage": "75.20%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "8",
        "Enroll Section": "A"
    },
    {
        "S.No.": 5,
        "Name": "UPENDRA BEHERA",
        "ID": "2117070130200013",
        "Year": "2021-22",
        "Class": "pioneer",
        "Section": "A",
        "Overall Marks Obtained": "210",
        "Total Marks": "250",
        "Percentage": "84.00%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "8",
        "Enroll Section": "A"
    }
]