export const std6=[
    {
        "S.No.": 1,
        "Name": "ADYA AHANA MANGARAJ",
        "Student ID": "2117070130200028",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "210",
        "Total Marks": "250",
        "Percentage": "84.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "7",
        "Enroll Section": "A"
    },
    {
        "S.No.": 2,
        "Name": "DIBYAJYOTI BARAL",
        "Student ID": "2117070680100070",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "208",
        "Total Marks": "250",
        "Percentage": "83.20%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "7",
        "Enroll Section": "A"
    },
    {
        "S.No.": 3,
        "Name": "JASHODA PARIDA",
        "Student ID": "2117070130200040",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "195",
        "Total Marks": "250",
        "Percentage": "78.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "7",
        "Enroll Section": "A"
    },
    {
        "S.No.": 4,
        "Name": "KARUNASHIKTA SAMANTASINGHAR",
        "Student ID": "2117070130200033",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "188",
        "Total Marks": "250",
        "Percentage": "75.20%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "7",
        "Enroll Section": "A"
    },
    {
        "S.No.": 5,
        "Name": "KUNAL PAIKARAY",
        "Student ID": "2117070130200031",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "178",
        "Total Marks": "250",
        "Percentage": "71.20%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "7",
        "Enroll Section": "A"
    },
    {
        "S.No.": 6,
        "Name": "SMRUTI CHHOTARAY",
        "Student ID": "2117070130200041",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "181",
        "Total Marks": "250",
        "Percentage": "72.40%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "7",
        "Enroll Section": "A"
    },
    {
        "S.No.": 7,
        "Name": "SUBHAM SWAIN",
        "Student ID": "2117070130200039",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "192",
        "Total Marks": "250",
        "Percentage": "76.80%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "7",
        "Enroll Section": "A"
    }
]