export const std4=
[
    {
        "S.No.": 1,
        "Name": "ADITYA MAHARANA",
        "Student ID": "2117070130200188",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "156",
        "Total Marks": "200",
        "Percentage": "78.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    },
    {
        "S.No.": 2,
        "Name": "AMREETA SAHOO",
        "Student ID": "2117070130200194",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "165",
        "Total Marks": "200",
        "Percentage": "82.50%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    },
    {
        "S.No.": 3,
        "Name": "ANSHUMAN JENA",
        "Student ID": "2117070130200183",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "147",
        "Total Marks": "200",
        "Percentage": "73.50%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    },
    {
        "S.No.": 4,
        "Name": "ARAVIND PAIKARAY",
        "Student ID": "2117070130200187",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "162",
        "Total Marks": "200",
        "Percentage": "81.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    },
    {
        "S.No.": 5,
        "Name": "BUBU PALAI",
        "Student ID": "2117070130200192",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "165",
        "Total Marks": "200",
        "Percentage": "82.50%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    },
    {
        "S.No.": 6,
        "Name": "GURUDEV SUNDARAY",
        "Student ID": "2117070130200173",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "171",
        "Total Marks": "200",
        "Percentage": "85.50%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    },
    {
        "S.No.": 7,
        "Name": "IPSITA PRADHAN",
        "Student ID": "2117070130200172",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "178",
        "Total Marks": "200",
        "Percentage": "89.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    },
    {
        "S.No.": 8,
        "Name": "MUKESH MAHARANA",
        "Student ID": "2117070130200178",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "154",
        "Total Marks": "200",
        "Percentage": "77.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    },
    {
        "S.No.": 9,
        "Name": "NARMADA BARAL",
        "Student ID": "2117070130200182",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "144",
        "Total Marks": "200",
        "Percentage": "72.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    },
    {
        "S.No.": 10,
        "Name": "SAHIL PALAI",
        "Student ID": "2117070130200191",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "164",
        "Total Marks": "200",
        "Percentage": "82.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    },
    {
        "S.No.": 11,
        "Name": "SAUBHAGYA NAYAK",
        "Student ID": "2117070130200176",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "173",
        "Total Marks": "200",
        "Percentage": "86.50%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    },
    {
        "S.No.": 12,
        "Name": "SMRUTI PRASAD MAHARANA",
        "Student ID": "2117070130200184",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "139",
        "Total Marks": "200",
        "Percentage": "69.50%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    },
    {
        "S.No.": 13,
        "Name": "SOMYARANJAN MAHARANA",
        "Student ID": "2117070130200189",
        "Year": "2021-22",
        "Class": "4",
        "Section": "A",
        "Overall Marks Obtained": "165",
        "Total Marks": "200",
        "Percentage": "82.50%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "4",
        "Enroll Section": "A"
    }
]