export const std5=[
    {
        "S.No.": 1,
        "Name": "AJIT SWAIN",
        "Student ID": "2117070130200140",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "210",
        "Total Marks": "250",
        "Percentage": "84.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 2,
        "Name": "ANKITA SENA",
        "Student ID": "2117070130200116",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "201",
        "Total Marks": "250",
        "Percentage": "80.40%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 3,
        "Name": "ARADHANA MAHARANA",
        "Student ID": "2117070130200117",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "184",
        "Total Marks": "250",
        "Percentage": "73.60%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 4,
        "Name": "ASIN MANGARAJ",
        "Student ID": "2117071740200002",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "196",
        "Total Marks": "250",
        "Percentage": "78.40%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 5,
        "Name": "AYUSH CHHOTARAY",
        "Student ID": "2117070130200126",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "212",
        "Total Marks": "250",
        "Percentage": "84.80%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 6,
        "Name": "BISWAJIT PAIKARAY",
        "Student ID": "2117070130200114",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "178",
        "Total Marks": "250",
        "Percentage": "71.20%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 7,
        "Name": "DINESH RANA",
        "Student ID": "2117070130200115",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "195",
        "Total Marks": "250",
        "Percentage": "78.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 8,
        "Name": "MADHUSMITA MAHARANA",
        "Student ID": "2117070130200142",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "192",
        "Total Marks": "250",
        "Percentage": "76.80%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 9,
        "Name": "OM BALABANTARAY",
        "Student ID": "2117070130200120",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "178",
        "Total Marks": "250",
        "Percentage": "71.20%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 10,
        "Name": "OMM SUNDARAY",
        "Student ID": "2117070130200113",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "195",
        "Total Marks": "250",
        "Percentage": "78.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 11,
        "Name": "PAYAL NAYAK",
        "Student ID": "2117070130200124",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "215",
        "Total Marks": "250",
        "Percentage": "86.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 12,
        "Name": "PRADYUMNA BARIK",
        "Student ID": "2117070130200118",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "213",
        "Total Marks": "250",
        "Percentage": "85.20%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 13,
        "Name": "PRASANTA KUMAR PAIKARAY",
        "Student ID": "2117070130200001",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "190",
        "Total Marks": "250",
        "Percentage": "76.00%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    },
    {
        "S.No.": 14,
        "Name": "RATIKANTA BEHERA",
        "Student ID": "2117070130200141",
        "Year": "2021-22",
        "Class": "5",
        "Section": "A",
        "Overall Marks Obtained": "189",
        "Total Marks": "250",
        "Percentage": "75.60%",
        "Result": "P",
         Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "5",
        "Enroll Section": "A"
    }
]
