export const std6=[
    {
        "S.No.": 1,
        "Name": "CHINMAY PALAI",
        "Student ID": "2117070130200018",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "185",
        "Total Marks": "250",
        "Percentage": "74.00%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "6",
        "Enroll Section": "A"
    },
    {
        "S.No.": 2,
        "Name": "GITANJALI MAHARANA",
        "Student ID": "2117070130200016",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "196",
        "Total Marks": "250",
        "Percentage": "78.40%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "6",
        "Enroll Section": "A"
    },
    {
        "S.No.": 3,
        "Name": "KAJAL BEHERA",
        "Student ID": "2117070130200102",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "201",
        "Total Marks": "250",
        "Percentage": "80.40%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "6",
        "Enroll Section": "A"
    },
    {
        "S.No.": 4,
        "Name": "KUMAR GAURAB NAYAK",
        "Student ID": "2117070130200021",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "176",
        "Total Marks": "250",
        "Percentage": "70.40%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "6",
        "Enroll Section": "A"
    },
    {
        "S.No.": 5,
        "Name": "LOPAMUDRA BARAL",
        "Student ID": "2117070130200025",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "210",
        "Total Marks": "250",
        "Percentage": "84.00%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "6",
        "Enroll Section": "A"
    },
    {
        "S.No.": 6,
        "Name": "RAKESH DAS",
        "Student ID": "2117070130200027",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "201",
        "Total Marks": "250",
        "Percentage": "80.40%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "6",
        "Enroll Section": "A"
    },
    {
        "S.No.": 7,
        "Name": "SAGINA PRADHAN",
        "Student ID": "2117070130200026",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "198",
        "Total Marks": "250",
        "Percentage": "79.20%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "6",
        "Enroll Section": "A"
    },
    {
        "S.No.": 8,
        "Name": "SANTOSH DAS",
        "Student ID": "2117070130200024",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "196",
        "Total Marks": "250",
        "Percentage": "78.40%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "6",
        "Enroll Section": "A"
    },
    {
        "S.No.": 9,
        "Name": "SMRUTI PUSPA PRIYADARSHINI",
        "Student ID": "2117070130200105",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "204",
        "Total Marks": "250",
        "Percentage": "81.60%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "6",
        "Enroll Section": "A"
    },
    {
        "S.No.": 10,
        "Name": "SOMYA RANJAN PRADHAN",
        "Student ID": "2117070130200108",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "201",
        "Total Marks": "250",
        "Percentage": "80.40%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "6",
        "Enroll Section": "A"
    },
    {
        "S.No.": 11,
        "Name": "SUBHAM PAIKARAY",
        "Student ID": "2117070130200020",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "198",
        "Total Marks": "250",
        "Percentage": "79.20%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "6",
        "Enroll Section": "A"
    },
    {
        "S.No.": 12,
        "Name": "SUPRAKASH DIBYADARSHAN",
        "Student ID": "2117070130200022",
        "Year": "2021-22",
        "Class": "6",
        "Section": "A",
        "Overall Marks Obtained": "170",
        "Total Marks": "250",
        "Percentage": "68.00%",
        "Result": "P",
        Image: "https://eshendetesia.com/images/user-profile.png",
        "Promoted Class": "6",
        "Enroll Section": "A"
    }
]